version: '3.4'
services:
  interfaceserver:
    build: .
    image: builder.mtab.ml:5000/stanford-quiz:${ID:-latest}
    command: sh /entry/entrypoint-interface.sh
    user: stanford
    working_dir: /stanford
    expose:
      - "8000"
    env_file:
      - docker/docker.env
    depends_on:
      - database
      - redis
  rqworker:
    image: builder.mtab.ml:5000/stanford-quiz:${ID:-latest}
    command: /entry/entrypoint-rqworker.sh
    user: stanford
    working_dir: /stanford
    expose:
      - "8000"
    env_file:
      - docker/docker.env
    depends_on:
      - database
      - redis
  scheduler:
    image: builder.mtab.ml:5000/stanford-quiz:${ID:-latest}
    command: /entry/entrypoint-rqscheduler.sh
    user: stanford
    working_dir: /stanford
    expose:
      - "8000"
    env_file:
      - docker/docker.env
    depends_on:
      - database
      - redis
  redis:
    image: redis:3.0-alpine
  database:
    image: postgres:9.5
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

