version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - media_files:/media_files
      - static:/static
    depends_on:
      - interfaceserver
  interfaceserver:
    build: .
    image: stanford-quiz
    command: /entry/entrypoint-interface.sh
    user: stanford
    working_dir: /stanford
    expose:
      - "8000"
    env_file:
      - docker/docker.env
    depends_on:
      - database
    volumes:
      - media_files:/media
      - static:/static
      - ./reports:/reports
  database:
    image: postgres:9.5
    volumes:
      - db_data:/var/lib/postgresql/data 
volumes:
   media_files:
   static:
   db_data:
