version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/config/nginx:/etc/nginx/conf.d
      - static:/static
      - media:/media
    depends_on:
      - interfaceserver
  interfaceserver:
    build: .
    command: /entry/entrypoint-interface.sh
    user: stanford
    working_dir: /stanford
    expose:
      - "8000"
    env_file:
      - docker/docker.env
    depends_on:
      - database
#      - redis
    volumes:
      - static:/static
      - media:/media
      - ./reports:/reports
#  workerserver:
#    build: .
#    command: /entry/entrypoint-worker.sh
#    user: stanford
#    working_dir: /stanford
#    env_file:
#      - docker/docker.env
#    depends_on:
#      - database
#      - redis
  database:
    image: postgres:9.5
    volumes:
      - db_data:/var/lib/postgresql/data 
#  redis:
#    image: redis:3.0-alpine
volumes:
   static:
   media:
   db_data:
