version: '3.4'
services:
  interfaceserver:
    build: .
    image: builder.pernixsoft.ml:5000/stanford-quiz:${ID:-latest}
    command: sh /entry/entrypoint-interface.sh
    user: stanford
    working_dir: /stanford
    expose:
      - "8000"
    env_file:
      - docker/docker.env
    depends_on:
      - database
  database:
    image: postgres:9.5

