version: '3.4'
services:
  reactserver:
    build:
      context: .
      target: react-pkg
    ports:
      - "3000:3000"
    working_dir: /stanford
    command: sh -c "npm install package.json; node react_server.js"
    volumes:
      - ./stanford/:/stanford/
  interfaceserver:
    ports:
      - "8000:8000"
    depends_on:
      - reactserver
    volumes:
      - ./stanford:/stanford
  database:
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
