version: '3'
services:
  nginx:
    ports:
      - "80:80"
    volumes:
      - ./docker/config/nginx/stanford.conf:/etc/nginx/conf.d/default.conf
  database:
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: