version: '2'
services:
  interfaceserver:
    build:
      context: .
      args:
        user_id: 1000
    ports:
      - "8000:8000"
    command: /entry/entrypoint-interface.sh
    user: stanford
    working_dir: /stanford
    expose:
      - "8000"
    env_file:
      - docker/docker.env
    depends_on:
      - database
#      - redis
    volumes:
      - static:/static
      - ./stanford:/stanford
  database:
    image: postgres:9.5
#  redis:
#    image: redis:3.0-alpine
volumes:
   static:
