version: '3.4'
services:
  nginx:
    ports:
      - "80:80"
    volumes:
      - ./docker/config/nginx/stanford.conf:/etc/nginx/conf.d/default.conf
      - ./stanford/frontend/assets/bundles:/static/bundles
  reactserver:
    build:
      context: .
      target: react-pkg
    working_dir: /stanford
    command: sh -c "npm install package.json; npm run watch"
    volumes:
      - ./stanford/webpack-stats.json:/stanford/webpack-stats.json
      - ./stanford/package.json:/stanford/package.json
      - ./stanford/frontend/bundles:/stanford/frontend/bundles
  interfaceserver:
    depends_on:
      - reactserver
    volumes:
      - ./stanford:/stanford
      - ./stanford/frontend/assets/bundles:/static/bundles
  database:
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: