version: '3'
services:
  nginx:
    ports:
      - "443:443"
    volumes:
      - ./docker/config/nginx/production.conf.template:/nginx.conf.template
      - /docker-volumes/etc/letsencrypt/live/${STANFORD_HOST}/fullchain.pem:/etc/letsencrypt/live/${STANFORD_HOST}/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/${STANFORD_HOST}/privkey.pem:/etc/letsencrypt/live/${STANFORD_HOST}/privkey.pem
      - /docker-volumes/data/letsencrypt:/usr/share/nginx/html
      - nginx_logs:/logs
    command: /bin/bash -c "envsubst '$$STANFORD_HOST' < /nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      - STANFORD_HOST=pernixsoft.ml
  interfaceserver:
    environment:
      - DJANGO_SSL=TRUE
volumes:
  nginx_logs:
