version: '3.4'
services:
  nginx:
    restart: always
    image: nginx:latest
    depends_on:
      - interfaceserver
    container_name: stanford-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./docker/config/nginx/production.conf.template:/nginx.conf.template
      - /docker-volumes/etc/letsencrypt/live/${STANFORD_HOST}/fullchain.pem:/etc/letsencrypt/live/${STANFORD_HOST}/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/${STANFORD_HOST}/privkey.pem:/etc/letsencrypt/live/${STANFORD_HOST}/privkey.pem
      - /docker-volumes/data/letsencrypt:/usr/share/nginx/html
      - nginx_logs:/logs
      - media_files:/media_files
      - static:/static
    command: /bin/bash -c "envsubst '$$STANFORD_HOST' < /nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      - STANFORD_HOST
  interfaceserver:
    restart: always
    environment:
      - DJANGO_SSL=TRUE
    deploy:
      replicas: 5
    volumes:
      - media_files:/media
      - static:/static
  rqworker:
    deploy:
      replicas: 5
  database:
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
  watchtower:
    image: v2tec/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    command: --interval 30
volumes:
  db_data:
  nginx_logs:
  media_files:
  static:
